# Generated by Django 6.1.1 on 2026-09-22 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('problem_description', models.TextField(blank=True, default='')),
                ('dataset_file', models.FileField(upload_to='datasets/')),
                ('status', models.CharField(choices=[('created', 'Created'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('task_type', models.CharField(blank=True, choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=20, null=True)),
                ('target_column', models.CharField(blank=True, max_length=255, null=True)),
                ('best_model', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_name', models.CharField(blank=True, max_length=50, null=True)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('all_metrics', models.JSONField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, max_length=500, null=True)),
                ('top_features', models.JSONField(blank=True, null=True)),
                ('insights', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('metric_name', models.CharField(default='accuracy', max_length=50)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='projects.aiproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
